# Generated by Django 4.2.2 on 2025-07-29 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город который искал пользователь')),
                ('search_count', models.PositiveIntegerField(default=1, verbose_name='Сколько раз искали город')),
                ('last_search', models.DateTimeField(auto_now=True, verbose_name='Последняя дата поиска города')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-last_search'],
                'unique_together': {('user', 'city')},
            },
        ),
    ]
